version: '2'

services:
  web:
    build: .

    command: /usr/local/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - .:/code
    ports:
      - "80:80"
      - "8000:8000"
      - "8080:8080"
      - "9001:9001"
    env_file:
      - .env